### ISSUE TITLE
Consider using UIVisualEffectView with UIBlurEffect

### ISSUE THREAD

**Issue by hansstefan** [marmelroy/PeekPop#11]
Currently producing blur screenshots takes about 0.20 second on iphone 5s, and this time is added every time the peekPopPossible method is invoked. Using UIVisualEffectView takes no time to generate, which makes the peekPop gesture much faster. 

A plus is that all animations in the background are still visible (and blurred). The downside is that you cannot control blur radius, but this is only a visual downside.

**Comment by marmelroy** [comment]
Thanks @hansstefan. It is something I considered when creating PeekPop. The main downside is that a UIVisualEffectView can't be applied progressively in iOS8 (an essential part of the Peek/Pop interaction).
