### ISSUE TITLE
Retain cycle

### ISSUE THREAD

**Issue by MarcosMunoz** [marmelroy/PeekPop#19]
There is a retain cycle that avoids to release the memory of the view controller using the PeekPop. The references to view controller and delegates inside the library should be weak.

**Comment by MarcosMunoz** [comment]
Also for devices < 6S the gesture should be removed from the view in the deinit, otherwise the memory of the whole control will never be released.

**Comment by MrAdamBoyd** [comment]
I just submitted a pull request ( #21 ) to fix the delegates not being weak. I'm slightly confused about what you're talking about in the second comment though. Where exactly should the gesture be removed from the view?

**Comment by marmelroy** [comment]
Merged and released as 0.1.5. Thanks again @MrAdamBoyd.
