### ISSUE TITLE
Using Kingfisher and peek doesn't load image

### ISSUE THREAD

**Issue by davidlondono** [marmelroy/PeekPop#20]
Im using Kingfisher to download the images, and Im trying to show the a picture on peek mode, but it seams the view controller is going to be shown a screenshot is loaded or something, because the code gets to where it downloads, the callback is called when completed, but the actual Image is not shown

**Comment by benaneesh** [comment]
This works on an actual device with 3D Touch, but not on one without it.

**Comment by entreprenik2** [comment]
I was testing something similar yesterday. Here's what I've noticed:

- viewWillAppear doesn't get called in backward-compatible flow (works fine in force-touch enabled device). Same for viewWillDisappear
- An UIImageView in a peeked controller will only change its .image property ONCE inside the backward-compatible flow (works fine in force-touch enabled device).

So it seems something's fundamentally flawed in the graphics implementation of this framework.

@marmelroy
