### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by AkiraTaki** [marmelroy/PeekPop#29]
Do you have any plan to adapt it for Swift 3?
This is really great project and I wish to use it

**Comment by mathmatrix828** [comment]
#30 should fix this. Let me know if it has issues

**Comment by Myrenkar** [comment]
@marmelroy could you please do something with this issue? I would like to use this library but Swift 3 makes it unavailable.

**Comment by marmelroy** [comment]
Shipped as version 1.0
