### ISSUE TITLE
Not working on scroll

### ISSUE THREAD

**Issue by peymayesh** [marmelroy/PeekPop#9]
It works only on first scroll frame, on invisible content not working.
Even after scroll, first frame freezes.

In sample app, if change column to 1 you can see the results.

**Comment by marmelroy** [comment]
Thanks @peymayesh. Looks like there is indeed a bug there... looking into it...

**Comment by marmelroy** [comment]
Fixed with https://github.com/marmelroy/PeekPop/commit/2341c6707ad216646794317c3624a9e481fa65a3. Thanks again @peymayesh.

**Comment by peymayesh** [comment]
Thank you so much👌
